// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igplzgvrpmasefoaaxtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncGx6Z3ZycG1hc2Vmb2FheHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzI1NjMsImV4cCI6MjA2MTc0ODU2M30.wxh0cNr4CmijSYpj9IntHFB-pTlaTkSfqZAVwDtf5po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);